@startuml

|Final_Client|
start
: Enter menu "Mes communautés";
|USSD|
: Get bundle info (community_id);
If ( OK) then
    else if (TimeoutException)
    :retry 3 times <
    stop
    else
    #red:Error(ERR_ENR01)<
    stop
endif
|Talend|
: Get bundle info  (community_id);
If ( OK) then
    else if (TimeoutException)
    :retry 3 times <
    stop
    else
    #red:Error(ERR_ENR01)<
    stop
endif
|Gateway|
: Get bundle  info (community_id);
If ( OK) then
    else if (TimeoutException)
    :retry 3 times <
    stop
    else
    #red:Error(ERR_ENR01)<
    stop
endif
|BundleMicroservice|
: Get bundle  info(community_id);

end
@enduml